### ISSUE TITLE
Backport 1.18.2

### ISSUE THREAD

**Issue by serega404** [syorito-hatsuki/bluemap-advanced-marker#5]
Hello, I would really like to use your mod on 1.18.2. if it's not difficult for you, please port it to 1.18.2.

**Comment by syorito-hatsuki** [comment]
Currently I don't have time do any update. Multiply deadlines on other projects. When I got free time I do backport

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/bam/version/2022.11.1
